import { GoogleGenAI, Type, Schema } from "@google/genai";
import { ComplianceResult } from '../types';

// Initialize Gemini Client
const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Edit the ID photo based on instructions using Gemini.
 */
export const editIdPhoto = async (
  imageBase64: string,
  promptInstruction: string
): Promise<string> => {
  const ai = getClient();
  const model = 'gemini-2.5-flash-image'; // Using flash-image for faster edits

  // Remove data URL prefix if present for the API call
  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: `You are an expert ID Photo Stylist. 
            Task: Edit the provided ID photo strictly following this instruction: "${promptInstruction}".
            
            Strict Guidelines:
            1. Maintain the identity of the person perfectly. Facial features must not change significantly unless requested (e.g. slight smile).
            2. The output must be a professional ID photo (high quality, studio lighting).
            3. Do not crop the head too tightly. Keep aspect ratio.
            4. If changing background, ensure clean hair segmentation.
            5. Return ONLY the image.`
          },
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg' 
            }
          }
        ]
      },
      // We don't use responseMimeType here because we want the model to generate the image bytes
      // effectively, but for gemini-2.5-flash-image, we look for inlineData in response.
    });

    // Check for image in response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Edit Error:", error);
    throw error;
  }
};

/**
 * Check compliance of the photo against standard ID regulations.
 */
export const checkCompliance = async (imageBase64: string): Promise<ComplianceResult> => {
  const ai = getClient();
  const model = 'gemini-2.5-flash'; // Flash is sufficient for analysis

  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  const complianceSchema: Schema = {
    type: Type.OBJECT,
    properties: {
      isCompliant: { type: Type.BOOLEAN },
      score: { type: Type.NUMBER, description: "Compliance score from 0 to 100" },
      issues: { 
        type: Type.ARRAY, 
        items: { type: Type.STRING },
        description: "List of specific compliance issues (e.g., 'Brows covered', 'Mouth open')"
      }
    },
    required: ["isCompliant", "score", "issues"]
  };

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: `Analyze this image for strict Passport/ID photo compliance. 
            Check for:
            1. Even lighting (no harsh shadows).
            2. Neutral expression or natural smile (mouth closed).
            3. Eyes open and clearly visible (no glare on glasses).
            4. Eyebrows and ears visible (hair not covering key features).
            5. Head centered and forward-facing.
            6. Plain background.`
          },
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg'
            }
          }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: complianceSchema
      }
    });

    if (response.text) {
      return JSON.parse(response.text) as ComplianceResult;
    }
    
    throw new Error("Failed to parse compliance check.");

  } catch (error) {
    console.error("Compliance Check Error:", error);
    return {
      isCompliant: false,
      score: 0,
      issues: ["System error checking compliance."]
    };
  }
};